version: '3.3'

volumes:
  pg_data:
  static:
  media:
  
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: galei4/foodgram_backend
    build: ../backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: galei4/foodgram_frontend
    build: ../frontend/
    volumes:
      - static:/static
  gateway:
    image: galei4/foodgram_gateway
    ports:
      - "9000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/static/api/docs/
      - static:/static
      - media:/media
    depends_on:
      - backend