# Generated by Django 4.2.4 on 2023-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipies",
            "0003_favorite_shoppinglist_alter_recipe_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "default_related_name": "favorites",
                "ordering": ["-id"],
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "default_related_name": "ingredient",
                "ordering": ("-name",),
                "verbose_name": "Ингридиент",
                "verbose_name_plural": "Ингридиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "default_related_name": "recipies",
                "ordering": ("-name",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppinglist",
            options={
                "default_related_name": "shopping_list",
                "ordering": ["-id"],
                "verbose_name": "Список покупок",
                "verbose_name_plural": "Списки покупок",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "default_related_name": "tag",
                "ordering": ("-name",),
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
            },
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(
                max_length=200, verbose_name="Единицы измерения"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
    ]
